name: testcases

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ["3.11", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install package and test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest

      - name: Run tests
        run: pytest tests/ -v

      - name: Test CLI smoke tests
        run: |
          python -m r7 --help || python r7.py --help
          python -m r7 config show || python r7.py config show

  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Install linting tools
        run: pip install ruff
        
      - name: Run ruff check
        run: ruff check . || true  # Don't fail on linting issues yet
        
      - name: Run ruff format check
        run: ruff format --check . || true  # Don't fail on formatting issues yet